### ISSUE TITLE
Attempt to invoke virtual method 'void android.view.View.setSelected(boolean)' on a null object reference

### ISSUE THREAD

**Issue by Imangadzhiev** [h6ah4i/android-tablayouthelper#8]
Hi, I updated sdk version to 24, and appcompat to v7:24:0:0 and design:24:0:0 and launched app, and app crashed:

`Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.View.setSelected(boolean)' on a null object reference
at android.support.design.widget.TabLayout$Tab.setCustomView(TabLayout.java:1298)
at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.onUpdateTab(TabLayoutHelper.java:204)
at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.updateTab(TabLayoutHelper.java:351)
at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.setTabsFromPagerAdapter(TabLayoutHelper.java:323)
at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.setupWithViewPager(TabLayoutHelper.java:302)
at com.h6ah4i.android.tablayouthelper.TabLayoutHelper.<init>(TabLayoutHelper.java:90)
at com.my.app.MainActivity.onCreate(MainActivity.java:100)
at android.app.Activity.performCreate(Activity.java:6092)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595) 
at android.app.ActivityThread.access$800(ActivityThread.java:178) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470) 
at android.os.Handler.dispatchMessage(Handler.java:111) 
at android.os.Looper.loop(Looper.java:194) 
at android.app.ActivityThread.main(ActivityThread.java:5624) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754) `

my.app.MainActivity

`100. TabLayoutHelper mTabLayoutHelper = new TabLayoutHelper(tabLayout,viewPager);
101. mTabLayoutHelper.setAutoAdjustTabModeEnabled(true);`
If i change sdk version to 23 and AppCompat to v7:23:7:0: and design to 23:7:0 , all works

**Comment by h6ah4i** [comment]
Thank you for the issue report. I will take a look at it.

**Comment by h6ah4i** [comment]
Hi. I have not tested it yet, but it seems a support library's issue. The issue has been reported to [AOSP](https://code.google.com/p/android/issues/detail?id=214753), and it is already fixed in support library v24.1.0.

> TabLayout.setCustomView(null) results in NullPointerException (AOSP issue)

ref.) https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by h6ah4i** [comment]
I have just confirmed that TabLayoutHelper works with support library v24.1.0.
